let g:indentLine_enabled=1
" let g:indentLine_char = '│'
let g:indentLine_char = '⋮'
" let g:indentLine_char = '┊'
" let g:indentLine_char = ''
" let g:indentLine_leadingSpaceEnabled = 1
" let g:indentLine_char = '·'
" let g:indentLine_leadingSpaceChar = '·'
" let g:indentLine_noConcealCursor=""
